### ISSUE TITLE
Adding tracks to playlist

### ISSUE THREAD

**Issue by stevetoro** [daveoy/react-capstone-jammming#3]
https://github.com/daveoy/react-capstone-jammming/blob/master/src/Components/App/App.js#L21-L37

There's a lot going on in this method.

Instead of using `forEach` and an external `trackInPlaylist` Boolean variable and related logic, could you use another iterator method like `some` or `find` that tells you exactly what you need to know and returns the Boolean itself?

For example:

```javascript
let trackExists = this.state.playlistTracks.some( _track => _track.id == track.id);
if (!trackExists)
  // setState
```

**Comment by daveoy** [comment]
ah yes it could be made simpler for sure. this method is structured this way because of two this:

1) my background is in python and that sort of boolean variable check is something i do alllll the time, which is bad, and
2) the instructions seemed to point to developing this method this way -- im still fairly new to javascript so i'll rewrite this guy and try to make it more conensed.
